AllCops:
  Exclude:
    - '*/pkg/**/*'
    - 'integration-tests/apps/**/*'

Lint/Eval:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/ClassLength:
  Max: 330

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 115

Metrics/MethodLength:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 10

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBody:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false

Style/UnneededCapitalW:
  Enabled: false
